/**
 * Multi-provider AI adapter, CLAUDE.md §9, design-spec §12.
 *
 * The guardrail that makes this safe to attach to a teaching tool:
 *
 *   Layer A (symbolic) is the source of truth. It is deterministic TypeScript
 *   and it never asks a model anything.
 *   Layer B (this file) only ever RE-EXPLAINS Layer A's verified content.
 *
 * So the model is handed the node's authored text plus the numbers the toy
 * model already computed, and is told in the system prompt that it may not
 * introduce facts or do arithmetic. The mechanics can't be corrupted by a loose
 * answer because they were calculated, not spoken.
 *
 * Key handling: held in memory for the page session only. Never written to
 * localStorage, never bundled, never sent anywhere except the provider the user
 * chose. Browser-side keys are visible in devtools, the UI says so plainly.
 */

export type ProviderId = 'anthropic' | 'openai' | 'openrouter' | 'google' | 'lmstudio';

export interface ProviderSpec {
  id: ProviderId;
  label: string;
  endpoint: string;
  /** Where the user gets a key. */
  keysUrl: string;
  defaultModel: string;
  /** Suggestions offered in a datalist; the field stays free text. */
  modelSuggestions: string[];
  /** Shown under the key field. */
  keyHint: string;
  /** Shown under the model field. Separate on purpose, they are different questions. */
  modelHint: string;
  /** Whether this provider takes OpenRouter's `reasoning` request parameter. */
  supportsReasoning?: boolean;
  /**
   * Runs on the reader's own machine and wants no key at all.
   *
   * Worth its own flag rather than an empty-string special case, because the
   * key check is what decides whether the adapter is available, and a local
   * model with no key is available in every sense that matters.
   */
  keyless?: boolean;
  /**
   * Where to ask the key what it can actually reach.
   *
   * Hardcoding model names was a mistake with a delayed fuse: the list is
   * right on the day it is written and silently wrong months later, and the
   * reader discovers it as a 404 they cannot act on. Providers retire names,
   * and some are withheld from new accounts entirely, so the only reliable
   * answer to "which model should I use" comes from the account itself.
   */
  listUrl?: string;
}

/**
 * One turn of a follow-up conversation.
 *
 * `reasoningDetails` exists because OpenRouter is explicit that, when
 * reasoning is enabled, the blocks must be passed back **completely
 * unmodified**. "the entire sequence of consecutive reasoning blocks must
 * match the outputs generated by the model during the original request; you
 * cannot rearrange or modify the sequence." So it is carried as an opaque
 * value: never parsed, never reshaped, never merged.
 */
export interface Turn {
  role: 'user' | 'assistant';
  content: string;
  reasoningDetails?: unknown;
}

export interface AskResult {
  text: string;
  /** Opaque. Store it and hand it straight back on the next turn. */
  reasoningDetails?: unknown;
}

/**
 * Anthropic model IDs are the verified current set. The other providers' model
 * names change often enough that hardcoding a list would go stale and mislead,
 * so those fields are free text with a placeholder, the user pastes whatever
 * their account has access to.
 */
export const PROVIDERS: Record<ProviderId, ProviderSpec> = {
  anthropic: {
    id: 'anthropic',
    label: 'Claude (Anthropic)',
    endpoint: 'https://api.anthropic.com/v1/messages',
    listUrl: 'https://api.anthropic.com/v1/models?limit=100',
    keysUrl: 'https://console.anthropic.com/settings/keys',
    defaultModel: 'claude-opus-5',
    modelSuggestions: ['claude-opus-5', 'claude-sonnet-5', 'claude-haiku-4-5'],
    keyHint: 'Keys start with sk-ant-.',
    modelHint: 'Pick from the list, or type any model your account can reach.',
  },
  openai: {
    id: 'openai',
    label: 'OpenAI',
    endpoint: 'https://api.openai.com/v1/chat/completions',
    listUrl: 'https://api.openai.com/v1/models',
    keysUrl: 'https://platform.openai.com/api-keys',
    defaultModel: '',
    modelSuggestions: [],
    keyHint: 'Keys start with sk-.',
    modelHint: 'Type a model name your account can use, e.g. a current gpt-* model.',
  },
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    endpoint: 'https://openrouter.ai/api/v1/chat/completions',
    listUrl: 'https://openrouter.ai/api/v1/models',
    keysUrl: 'https://openrouter.ai/keys',
    // `openrouter/free` is OpenRouter's Free Models Router: it picks a free
    // model at random and filters for the features a request needs. Defaulting
    // to it removes the worst friction in this panel, otherwise a learner has
    // to go and find a model slug before they can ask anything.
    defaultModel: 'openrouter/free',
    modelSuggestions: ['openrouter/free', 'openrouter/auto'],
    keyHint: 'Keys start with sk-or-.',
    modelHint:
      'openrouter/free costs nothing and picks a free model for you (50 requests/day, more with credit). openrouter/auto picks the best model for the request. Or type any vendor/model slug.',
    supportsReasoning: true,
  },
  lmstudio: {
    id: 'lmstudio',
    label: 'LM Studio (on this machine)',
    // LM Studio serves an OpenAI-compatible API, so it reuses that path whole.
    endpoint: 'http://localhost:1234/v1/chat/completions',
    listUrl: 'http://localhost:1234/v1/models',
    keysUrl: 'https://lmstudio.ai/docs/app/api/endpoints/openai',
    keyless: true,
    defaultModel: '',
    modelSuggestions: [],
    keyHint:
      'No key, no account, no cost. Install LM Studio, download a model, and start its local server on port 1234.',
    modelHint:
      'Press Find models once the server is running. Nothing you type leaves your machine. If the request fails, turn on CORS in LM Studio: the page is served from a file, so the browser treats localhost as a different origin.',
  },
  google: {
    id: 'google',
    label: 'Gemini (Google)',
    // The model name goes in the PATH, not the body, so this is a template.
    // `createAdapter` substitutes it; nothing else in this file does that.
    endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent',
    listUrl: 'https://generativelanguage.googleapis.com/v1beta/models?pageSize=200',
    keysUrl: 'https://aistudio.google.com/apikey',
    // Deliberately empty. Google retires model names and withholds some from
    // new accounts, so any name written here is a 404 waiting to happen for
    // somebody. "Find models" fills this in from the key instead.
    defaultModel: '',
    modelSuggestions: [],
    keyHint: 'Get one free from Google AI Studio. Keys start with AIza.',
    modelHint:
      'Paste your key, then press Find models. It lists what your key can actually reach and picks a fast, cheap one.',
  },
};

export interface AskRequest {
  /** The verified lesson content the answer must stay inside. */
  grounding: string;
  question: string;
  /** Earlier turns, for follow-ups. Empty for the first question. */
  history?: Turn[];
  signal?: AbortSignal;
}

export interface AIAdapter {
  available: boolean;
  ask(req: AskRequest): Promise<AskResult>;
}

/**
 * The default. The app is fully functional on Layer A alone, no key, no
 * network, every lesson and every number works. This adapter exists so the UI
 * has something to render "not configured" against.
 */
export const NullAdapter: AIAdapter = {
  available: false,
  async ask() {
    throw new Error('No API key configured.');
  },
};

/**
 * design-spec §12's guardrail, written out. The model is a re-explainer, not an
 * authority: it must not compute, must not add facts, and must say so when the
 * answer is not in the material.
 */
export function systemPrompt(): string {
  return [
    'You are a patient teaching assistant embedded in an interactive lesson about how large language models work.',
    '',
    'You may ONLY re-explain the verified lesson content provided below, in simpler or different terms.',
    '',
    'Hard rules:',
    '- Do not introduce facts that are not in the material.',
    '- Do not compute, recompute, estimate or alter any number. The numbers below were calculated by the lesson itself and are correct; quote them, never derive new ones.',
    '- If the question cannot be answered from the material, say so plainly and point to what the material does cover. Do not guess.',
    '- Keep answers to about four sentences. Warm, plain, second person, no jargon without a gloss.',
    '- Never claim to have run or verified anything.',
  ].join('\n');
}

function userPrompt(req: AskRequest): string {
  return [
    '=== VERIFIED LESSON CONTENT (the only thing you may draw on) ===',
    req.grounding,
    '=== END VERIFIED CONTENT ===',
    '',
    `Learner's question: ${req.question}`,
  ].join('\n');
}

/** Turn a failed fetch into something a learner can act on. */
async function describeFailure(res: Response, provider: ProviderSpec): Promise<string> {
  let detail = '';
  try {
    const body: unknown = await res.json();
    if (body && typeof body === 'object') {
      const err = (body as { error?: { message?: string } }).error;
      if (err?.message) detail = `, ${err.message}`;
    }
  } catch {
    /* body wasn't JSON; the status alone will have to do */
  }

  if (res.status === 401 || res.status === 403) {
    return `${provider.label} rejected the key (${res.status})${detail}. Check it at ${provider.keysUrl}.`;
  }
  if (res.status === 404) {
    // "Try a different one" is useless advice when the reader has no way to
    // know which ones exist, and model names are retired often enough that
    // this is the failure people actually hit. Point at the thing that answers
    // the question instead of restating it.
    return (
      `${provider.label} does not recognise that model name (404)${detail}. ` +
      (provider.listUrl
        ? 'Press "Find models" in the connection panel. It lists what your key can actually reach.'
        : 'Check the model name against your account.')
    );
  }
  if (res.status === 429) {
    return `${provider.label} rate-limited the request (429)${detail}. Wait a moment and retry.`;
  }
  if (res.status >= 500) {
    return `${provider.label} had a server error (${res.status})${detail}. Retry shortly.`;
  }
  return `${provider.label} returned ${res.status}${detail}.`;
}

/**
 * Anthropic's Messages API.
 *
 * Wire details that matter: auth is `x-api-key` (not a bearer token), the
 * `anthropic-version` header is required, and the response body is a list of
 * content blocks. The text lives in the blocks whose type is 'text', not in a
 * single string field.
 *
 * `anthropic-dangerous-direct-browser-access` is what opts a browser request
 * past CORS. The name is a warning, and it is accurate: a key used from a
 * browser is exposed to anyone with devtools. Fine for a local learning tool
 * with your own key; not something to ship to other people.
 */
async function askAnthropic(key: string, model: string, req: AskRequest): Promise<AskResult> {
  const p = PROVIDERS.anthropic;
  const res = await fetch(p.endpoint, {
    method: 'POST',
    signal: req.signal ?? null,
    headers: {
      'content-type': 'application/json',
      'x-api-key': key,
      'anthropic-version': '2023-06-01',
      'anthropic-dangerous-direct-browser-access': 'true',
    },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      system: systemPrompt(),
      messages: [
        ...(req.history ?? []).map((t) => ({ role: t.role, content: t.content })),
        { role: 'user', content: userPrompt(req) },
      ],
    }),
  });

  if (!res.ok) throw new Error(await describeFailure(res, p));

  const data = (await res.json()) as {
    content?: Array<{ type: string; text?: string }>;
    stop_reason?: string;
  };

  // A refusal returns HTTP 200 with an empty or partial content array, so the
  // blocks have to be checked rather than indexed.
  const text = (data.content ?? [])
    .filter((b) => b.type === 'text' && typeof b.text === 'string')
    .map((b) => b.text)
    .join('')
    .trim();

  if (!text) {
    if (data.stop_reason === 'refusal') {
      return {
        text: 'The model declined to answer that one. Try rephrasing, or read the layer above.',
      };
    }
    throw new Error('Anthropic returned no text.');
  }
  return { text };
}

/** OpenAI and OpenRouter share the chat-completions shape. */
async function askChatCompletions(
  p: ProviderSpec,
  key: string,
  model: string,
  req: AskRequest,
  reasoning: boolean,
): Promise<AskResult> {
  const headers: Record<string, string> = { 'content-type': 'application/json' };
  // A local server has nothing to authorise against.
  if (!p.keyless) headers.authorization = `Bearer ${key}`;
  if (p.id === 'openrouter') {
    // OpenRouter uses these for its public leaderboard; harmless and polite.
    headers['HTTP-Referer'] = 'https://github.com/arsurvey82/AILearning';
    headers['X-Title'] = 'LLM Learner';
  }

  // Prior turns are replayed verbatim. An assistant turn carries its
  // reasoning_details back UNMODIFIED. OpenRouter requires the sequence to
  // match exactly what the model produced, so it is spread in as received
  // rather than rebuilt.
  const history = (req.history ?? []).map((t) =>
    t.role === 'assistant' && t.reasoningDetails
      ? { role: t.role, content: t.content, reasoning_details: t.reasoningDetails }
      : { role: t.role, content: t.content },
  );

  const body: Record<string, unknown> = {
    model,
    messages: [
      { role: 'system', content: systemPrompt() },
      ...history,
      { role: 'user', content: userPrompt(req) },
    ],
  };

  // Off unless asked for. A four-sentence grounded re-explanation does not
  // need a reasoning pass, and OpenRouter bills reasoning tokens as output
  // tokens, on the free router that also burns the daily request budget
  // faster for no gain the learner can see.
  if (reasoning && p.supportsReasoning) body['reasoning'] = { enabled: true };

  const res = await fetch(p.endpoint, {
    method: 'POST',
    signal: req.signal ?? null,
    headers,
    body: JSON.stringify(body),
  });

  if (!res.ok) throw new Error(await describeFailure(res, p));

  const data = (await res.json()) as {
    choices?: Array<{ message?: { content?: string; reasoning_details?: unknown } }>;
    error?: { message?: string };
  };
  if (data.error?.message) throw new Error(`${p.label}: ${data.error.message}`);

  const msg = data.choices?.[0]?.message;
  const text = msg?.content?.trim();
  if (!text) throw new Error(`${p.label} returned no text.`);
  return { text, reasoningDetails: msg?.reasoning_details };
}

/**
 * Gemini, which is neither of the other two shapes.
 *
 * Three differences that all bite if you assume a chat-completions clone:
 *   - the model goes in the URL path, not the request body;
 *   - the system prompt is its own `systemInstruction` field rather than a
 *     message with role "system";
 *   - the assistant role is called "model", so replaying history with
 *     "assistant" is rejected.
 *
 * The key travels in `x-goog-api-key` rather than the query string, so it does
 * not end up in logs or in the browser's history.
 */
async function askGemini(
  p: ProviderSpec,
  apiKey: string,
  model: string,
  req: AskRequest,
): Promise<AskResult> {
  const url = p.endpoint.replace('{model}', encodeURIComponent(model));
  const res = await fetch(url, {
    method: 'POST',
    signal: req.signal ?? null,
    headers: { 'content-type': 'application/json', 'x-goog-api-key': apiKey },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: systemPrompt() }] },
      contents: [
        ...(req.history ?? []).map((t) => ({
          role: t.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: t.content }],
        })),
        { role: 'user', parts: [{ text: userPrompt(req) }] },
      ],
    }),
  });

  if (!res.ok) throw new Error(await describeFailure(res, p));

  const data = (await res.json()) as {
    candidates?: Array<{
      content?: { parts?: Array<{ text?: string }> };
      finishReason?: string;
    }>;
    promptFeedback?: { blockReason?: string };
  };

  // A blocked prompt comes back HTTP 200 with no candidates at all, so an
  // empty response has to be reported rather than rendered as a blank answer.
  if (data.promptFeedback?.blockReason) {
    throw new Error(
      `${p.label} declined to answer this one (${data.promptFeedback.blockReason}). The lesson above is unaffected.`,
    );
  }

  const cand = data.candidates?.[0];
  const text = (cand?.content?.parts ?? [])
    .map((part) => part.text ?? '')
    .join('')
    .trim();

  if (!text) {
    throw new Error(
      `${p.label} returned no text${cand?.finishReason ? ` (${cand.finishReason})` : ''}. Try rephrasing the question.`,
    );
  }
  return { text };
}

/* ------------------------------------------------------------------ *
 * Model discovery
 *
 * The alternative to a stale hardcoded list. Each provider publishes what a
 * given key can reach; this normalises the four different response shapes into
 * one list, filters out models that cannot answer a chat request at all
 * (embeddings, image and speech models), and offers a default.
 * ------------------------------------------------------------------ */

export interface ModelOption {
  id: string;
  label: string;
  /** Short, factual note from the provider, never our own claim about it. */
  note?: string;
  /** True when the provider says this one costs nothing. */
  free?: boolean;
}

/** Models that exist but cannot answer a chat request. */
const NOT_CHAT = /embed|embedding|moderation|whisper|tts|audio|image|imagen|veo|dall-e|vision-encoder|aqa|rerank/i;

/**
 * How good a fit a model is for THIS job, which is re-explaining one short
 * paragraph. That job wants cheap and fast far more than it wants clever, so
 * small models score highest.
 *
 * This is a heuristic over model NAMES, and it is worth being honest that
 * names are a weak signal. It exists to put a sensible option first, not to
 * be authoritative. The user can pick anything in the list.
 */
function score(m: ModelOption): number {
  const n = `${m.id} ${m.label}`.toLowerCase();
  let s = 0;
  if (m.free) s += 40;
  if (/flash|mini|haiku|small|lite|turbo/.test(n)) s += 30;
  if (/pro|opus|large|ultra/.test(n)) s -= 10;
  // Prefer newer: the highest version-looking number in the name.
  const versions = [...n.matchAll(/(\d+(?:\.\d+)?)/g)].map((x) => Number(x[1]));
  if (versions.length) s += Math.min(Math.max(...versions), 12);
  // Names that advertise an experiment or a cutoff date tend to disappear.
  if (/preview|exp|experimental|latest|\d{4}-\d{2}/.test(n)) s -= 8;
  return s;
}

/** Best first, by the heuristic above. */
export function rankModels(models: readonly ModelOption[]): ModelOption[] {
  return [...models].sort((a, b) => score(b) - score(a) || a.id.localeCompare(b.id));
}

/**
 * Ask the provider what this key can reach.
 *
 * Returns [] rather than throwing when the provider has no list endpoint, so
 * the caller can treat "cannot discover" and "discovered nothing" the same way
 *, both mean: fall back to typing a name.
 */
export async function listModels(
  provider: ProviderId,
  apiKey: string,
  signal?: AbortSignal,
): Promise<ModelOption[]> {
  const p = PROVIDERS[provider];
  if (!p.listUrl) return [];

  const headers: Record<string, string> =
    provider === 'anthropic'
      ? {
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01',
          'anthropic-dangerous-direct-browser-access': 'true',
        }
      : provider === 'google'
        ? { 'x-goog-api-key': apiKey }
        : { authorization: `Bearer ${apiKey}` };

  const res = await fetch(p.listUrl, { method: 'GET', headers, signal: signal ?? null });
  if (!res.ok) throw new Error(await describeFailure(res, p));

  const data = (await res.json()) as Record<string, unknown>;
  let out: ModelOption[] = [];

  if (provider === 'google') {
    // Google prefixes ids with "models/", and only some support generateContent.
    const models = (data.models ?? []) as Array<{
      name?: string;
      displayName?: string;
      description?: string;
      supportedGenerationMethods?: string[];
    }>;
    out = models
      .filter((m) => (m.supportedGenerationMethods ?? []).includes('generateContent'))
      .map((m) => ({
        id: (m.name ?? '').replace(/^models\//, ''),
        label: m.displayName || (m.name ?? '').replace(/^models\//, ''),
      }));
  } else if (provider === 'anthropic') {
    const models = (data.data ?? []) as Array<{ id?: string; display_name?: string }>;
    out = models.map((m) => ({ id: m.id ?? '', label: m.display_name || m.id || '' }));
  } else if (provider === 'openrouter') {
    const models = (data.data ?? []) as Array<{
      id?: string;
      name?: string;
      pricing?: { prompt?: string; completion?: string };
    }>;
    out = models.map((m) => {
      // OpenRouter publishes prices as decimal strings; "0" means free.
      const free =
        Number(m.pricing?.prompt ?? '1') === 0 && Number(m.pricing?.completion ?? '1') === 0;
      return { id: m.id ?? '', label: m.name || m.id || '', free, note: free ? 'free' : undefined };
    });
  } else {
    const models = (data.data ?? []) as Array<{ id?: string }>;
    out = models.map((m) => ({ id: m.id ?? '', label: m.id ?? '' }));
  }

  return rankModels(out.filter((m) => m.id && !NOT_CHAT.test(m.id)));
}

export interface AdapterConfig {
  provider: ProviderId;
  apiKey: string;
  model: string;
  /** Opt-in. See the comment at the request site for why it is off by default. */
  reasoning?: boolean;
}

export function createAdapter(cfg: AdapterConfig): AIAdapter {
  const p = PROVIDERS[cfg.provider];
  /* A local model is available with no key. Requiring one here is what made
     "free and private" impossible to offer at all. */
  if ((!cfg.apiKey.trim() && !p.keyless) || !cfg.model.trim()) return NullAdapter;
  return {
    available: true,
    async ask(req) {
      try {
        if (cfg.provider === 'anthropic') return await askAnthropic(cfg.apiKey, cfg.model, req);
        if (cfg.provider === 'google') return await askGemini(p, cfg.apiKey, cfg.model, req);
        return await askChatCompletions(p, cfg.apiKey, cfg.model, req, cfg.reasoning ?? false);
      } catch (e) {
        if (e instanceof DOMException && e.name === 'AbortError') throw e;
        // A browser fetch that never reaches the server throws TypeError with
        // no status. Almost always CORS or no network, and worth naming,
        // because "Failed to fetch" tells a learner nothing.
        if (e instanceof TypeError) {
          throw new Error(
            `Could not reach ${p.label}. This is usually a network problem, or the provider blocking direct browser requests. ` +
              `Check your connection, or try another provider.`,
          );
        }
        throw e;
      }
    },
  };
}
